services:
  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html:ro
    depends_on:
      - wordpress
    restart: always
    networks:
      - inception

  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception

  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    networks:
      - inception

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/natferna/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/natferna/data/wordpress

networks:
  inception:
    driver: bridge
