FROM debian:bullseye

RUN apt-get update && apt-get install -y \
	nginx \
	openssl \
 && rm -rf /var/lib/apt/lists/*

RUN rm -rf /var/www/html/*
RUN mkdir -p /etc/nginx/ssl

RUN openssl req -x509 -nodes -days 365 \
	-newkey rsa:2048 \
	-keyout /etc/nginx/ssl/inception.key \
	-out /etc/nginx/ssl/inception.crt \
	-subj "/C=ES/ST=Madrid/L=Madrid/O=42/OU=student/CN=natferna.42.fr"

COPY conf/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
